added technical challenge contribution
dextra/dextraquario pull request #103
Opened 2020-09-20 22:00 UTC by leonardobilia

# Obrigado pela sua contribuição

### IMPORTANTE!!

Para contribuições para o time de people connection!

* Lembre-se de colocar o nome da pessoa do time de people connection que você ajudou.
* Lembre-se de colocar a data em que você fez essa contribuição.
* Em caso de correção de teste de candidato, não precisa colocar o link do repositório, somente o nome da pessoa de people connection que você ajudou.

**NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

[x] marque aqui com um X se você leu este comunicado!

2020-09-29 22:30 UTC, tyemykuga requested changes
Olá Leonardo, tudo bem?

Agradecemos as contribuições que tem feito no Dextraquário, mas percebemos que alguns desafios que foram submetidos são muito simples.
 O objetivo da iniciativa é que as pessoas se desafiem a fazer algo diferente, aprender algo novo, etc. 
Vamos revisar todas as suas contribuições e se entendermos que não estão aderentes a ideia do projeto, ela serão removidas.

Obrigada!

2020-10-01 13:40 UTC, leonardobilia commented
@tyemykuga já encerraram as publicações no Dextraquário? Caso ainda não, poderia apontar quais considera muito simples para que possa remover do PR?

2020-10-01 13:57 UTC, tyemykuga reviewed
Como falei no comentário acima, estamos revisando todas as suas contribuições para validar se realmente foram aderentes a proposta do evento.
Assim que finalizarmos daremos um feedback.

2020-10-02 13:46 UTC, tyemykuga approved these changes

2020-10-02 13:46 UTC, merged