entrevista de QA
dextra/dextraquario pull request #115
Opened 2020-09-25 11:33 UTC by fellipemendes

# Obrigado pela sua contribuição

### IMPORTANTE!!

Para contribuições para o time de people connection!

* Lembre-se de colocar o nome da pessoa do time de people connection que você ajudou.
* Lembre-se de colocar a data em que você fez essa contribuição.
* Em caso de correção de teste de candidato, não precisa colocar o link do repositório, somente o nome da pessoa de people connection que você ajudou.

**NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

[X] marque aqui com um X se você leu este comunicado!

2020-09-25 11:33 UTC, fellipemendes commented
Sim, foram 2 entrevistas rsrs

2020-09-29 22:13 UTC, tyemykuga approved these changes

2020-09-29 22:22 UTC, tyemykuga commented on contributions/FellipeMendes/13.json
> +    "contributionLinkRepository": "http://www.programmr.com/embed.php?action=tf&path=fellipemendes//view/temp_1601037546/Challenge.java"
Olá Fellipe, tudo bem?

Agradecemos as contribuições que tem feito no Dextraquário, mas percebemos que esse desafio é bastante simples.
O objetivo da iniciativa é que as pessoas se desafiem a fazer algo diferente, aprender algo novo, etc.
Peço que revise essa contribuição por favor.

Obrigada!

2020-09-29 22:22 UTC, tyemykuga requested changes
Fiz um comentário sobre o desafio técnico enviado.

2020-09-29 22:28 UTC, fellipemendes commented on contributions/FellipeMendes/13.json
> +    "contributionLinkRepository": "http://www.programmr.com/embed.php?action=tf&path=fellipemendes//view/temp_1601037546/Challenge.java"
ooi, Tyemy. Tudo bem e vc?
Não sei se vc sabe, mas eu sou QA, não sou Dev. Não desenvolvo tanto (além dos testes automatizados). Isso pra mim é novo e busquei vários desafios onde eu entendesse o que era pedido e conseguisse aplicar sem achar soluções prontas. Conversei com o Elias sobre e ele disse que a ideia era essa e que valia a pena mandar.
Mas tudo bem, vou cancelar a PR.
Obrigado ;)

2020-09-29 22:48 UTC, tyemykuga commented on contributions/FellipeMendes/13.json
> +    "contributionLinkRepository": "http://www.programmr.com/embed.php?action=tf&path=fellipemendes//view/temp_1601037546/Challenge.java"
Eu sei sim que você é QA e que está na Dextra há um pouco mais de um ano.
Acredito que você já lide com coisas mais complexas, por isso pontuei a questão do desafio.
Mas tudo, vamos manter sua contribuição e obrigada por participar.

2020-09-30 00:55 UTC, fellipemendes commented on contributions/FellipeMendes/13.json
> +    "contributionLinkRepository": "http://www.programmr.com/embed.php?action=tf&path=fellipemendes//view/temp_1601037546/Challenge.java"
Um pouco mais do que isso. Siiiim, bem mais complexas de fato, mas é bom ver outras coisas que não se vê tanto.
atualizei a PR para remover minha participação. Obrigado!

2020-10-02 13:13 UTC, closed without merging