Feat/add contribution
dextra/dextraquario pull request #141
Opened 2021-02-04 14:21 UTC by thomaspl1

Adicionada tela para que os usuários enviem suas contribuições.

Trello: https://trello.com/c/Fnekxlcn/2-implementar-interface-de-submiss%C3%A3o-de-contribui%C3%A7%C3%B5es

2021-02-04 14:46 UTC, brconsani-dextra commented on lib/components/custom_dropdown.dart
> +          bottom: isLastItem ? Radius.zero : Radius.zero,
Se o `Radius` será sempre zero, porque a verificação?

2021-02-04 14:52 UTC, brconsani-dextra commented on lib/components/custom_dropdown.dart
> +    });
Como essa função anônima possui apenas uma instrução, poderia substituir pela _syntatic sugar_:
`setState(() => widget.itemHeight = height);`

2021-02-04 14:53 UTC, brconsani-dextra commented on lib/components/custom_dropdown.dart
> +              left: xPosition, top: yPosition + height, right: xPosition),
Adicionaria uma `,` depois de xPosition para o autoIdent indentar corretamente

2021-02-04 14:53 UTC, eliasreis54 commented on lib/components/custom_dropdown.dart
> +                          });
Em todos os lugares o `setState` é o mesmo, só muda o `text`.
Melhor extrair tudo isso pra uma função que recebe o `text` como parâmetro e faz o `setState`, ai da pra remover bastante código.

2021-02-04 14:54 UTC, brconsani-dextra commented on lib/components/custom_dropdown.dart
> +                height: 1,
Nesse caso, como o SizedBox é um componente não muito verboso, retiraria a `,` depois do `1`

2021-02-04 15:11 UTC, erickzanardo requested changes

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +  String text;
Todos os widgets, inclusive Stateful são imutáveis, estes atributos precisam ser final

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +    super.initState();
super.initState deveria ser a sua primeira chamada nesse método

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +      widget.itemHeight = height;
Widgets são imutáveis, vc não pode alterar suas propriedades.

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +    width = renderBox.size.width;
As alterações de variáveis deveriam estar dentro de uma chamada para o `setState`

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +    yPosition = offset.dy;
Essa operação toda está um tanto estranho, vi que vc está usando esses valores para construir um padding, teve algum motivo para isso ser necessário e não ter usado Widgets de layout direto?

2021-02-04 15:11 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +                            size: 24, color: Color.fromRGBO(161, 84, 48, 1))),
Existe um arquivo de paleta de cores, use uma cor de lá, ou crie essa lá casa não exista ainda.

2021-02-04 18:51 UTC, thomaspl1 commented on lib/components/custom_dropdown.dart
> +    yPosition = offset.dy;
Então, foi esse jeito que encontramos para que o menu do dropdown ficasse dentro do espaço que deve ficar, de outros jeitos ele estava se expandindo demais. Não conseguimos pensar outra maneira que funcionasse do tamanho correto. Acha que teria outro jeito ou podemos deixar assim?

2021-02-05 13:33 UTC, erickzanardo approved these changes
um pequeno comentário, mas já LGTM

2021-02-05 13:33 UTC, erickzanardo commented on lib/components/custom_dropdown.dart
> +  void setDropdownClickState(String option) {
Todo lugar que vc chama essa função, vc faz um setState. Sugestão: Coloque o setState aqui dentro, assim vc repete menos código, e fica mais fácil de entender que essa função está realmente alterando o estado do widget

2021-02-05 13:51 UTC, merged