feat/profile-interface
dextra/dextraquario pull request #145
Opened 2021-02-05 16:28 UTC by IamN5

Profile interface, with mocked data.

Trello Card: https://trello.com/c/KBZU9CAr/15-implementar-interface-do-perfil-do-usu%C3%A1rio

2021-02-05 16:55 UTC, erickzanardo requested changes

2021-02-05 16:55 UTC, erickzanardo commented on lib/common.dart
> +  static Widget contributionItem(Contribution contribution, int index,
Funções que retornam Widget para ser reutilizado é um anti pattern em Flutter pois ao fazer isso fugimos da árvore de build e perdemos algumas otimizações que o framework faz para nós, transforme isso em um stateless Widget mesmo.

2021-02-05 16:55 UTC, erickzanardo commented on lib/common.dart
> +  static Widget contributionItem(Contribution contribution, int index,
Funções que retornam Widget para ser reutilizado é um anti pattern em Flutter pois ao fazer isso fugimos da árvore de build e perdemos algumas otimizações que o framework faz para nós, transforme isso em um stateless Widget mesmo.

2021-02-05 16:55 UTC, erickzanardo commented on lib/overlays/profile_overlay.dart
> +  Widget _contributionNumber(ItemType type) {
Mesmo comentário aqui, transforme isso em um StatelessWidget

2021-02-05 17:17 UTC, IamN5 commented on lib/common.dart
> +  static Widget contributionItem(Contribution contribution, int index,
Valeu! Tinha visto alguém usando isso e assumi que era o correto, obrigado pelo aviso :)

2021-02-08 13:54 UTC, erickzanardo approved these changes

2021-02-08 14:06 UTC, merged