feat/aprovacao-contribuicoes
dextra/dextraquario pull request #161
Opened 2021-02-10 18:35 UTC by cassiamegumi

Aprovação das contribuições e correção de alguns erros.

2021-02-10 18:54 UTC, erickzanardo requested changes

2021-02-10 18:54 UTC, erickzanardo commented on lib/overlays/add_contribution_overlay.dart
> +                                                type = option;
Você está alterando uma variável do estado sem chamar o setState, está correto isso?

2021-02-10 18:54 UTC, erickzanardo commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
Esses futures não precisam ser inicializados no initState, eles poderiam ser passado diretamente pro futurebuilder. Com isso seu widget não teria estado e vc poderia usar o StatelessWidget mesmo.

2021-02-10 18:54 UTC, erickzanardo commented on lib/overlays/home_screen_overlay.dart
> +  Widget page(context, UserModel userModel, List<UserModel> topUsersList,
Não crie função que retornam widget para ser reutilizado, isso é um anti pattern em Flutter e pode levar a problemas de perfomance.

Transforme essa função em um widget genérico.

2021-02-10 18:54 UTC, erickzanardo commented on lib/overlays/profile_overlay.dart
> +                                            //   ContributionItem(
Código comentado pode ser removido.

2021-02-11 12:46 UTC, IamN5 commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
@erickzanardo Acho que na verdade precisamos que esse widget seja Stateful, pra que possamos re-renderizar ele quando uma contribuição for aprovada/reprovada, atualizando a lista de contribuições. Você pode confirmar isso pra gente?

2021-02-11 12:53 UTC, erickzanardo commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
Só olhando para o código não sei dizer, mas olhando para ele nesse momento, não vejo nenhum motivo para ele ser stateful, as únicas variáveis que são alteradas são os futures, mas ele podem ser passados diretamente pro `FutureBuilder` e não existe nenhum `setState` também.

2021-02-11 12:54 UTC, IamN5 commented on lib/overlays/add_contribution_overlay.dart
> +                                                type = option;
@erickzanardo  Quando a variável "type" é alterada, não é necessário que re-renderizemos esse widget, mesmo assim o mais correto seria considerar ela uma variável de estado?

2021-02-11 12:59 UTC, IamN5 commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
Na linha 142 passamos uma função que atualiza o state para o Widget (dentro do arquivo common.dart) que possui os botões de aprovar/reprovar, e que depois da ação de aprovar/reprovar é executada para atualizar a listagem de contribuições pendentes.

2021-02-11 13:02 UTC, erickzanardo commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
Justo, deixei essa linha passar, faz sentido manter como Stateful então. De qualquer maneira, ainda acho que vale a pena os futures serem passados direto pro FutureBuilder.

2021-02-11 13:11 UTC, IamN5 commented on lib/overlays/admin_overlay.dart
> +  Future<List<ContributionModel>> _dbContributions;
Beleza, valeu!

2021-02-11 17:45 UTC, erickzanardo approved these changes

2021-02-11 19:16 UTC, merged