Add contribuitions
dextra/dextraquario pull request #25
Opened 2020-09-02 18:06 UTC by leandropaes

2020-09-03 15:28 UTC, tyemykuga commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Teria o link do PR pra passar pra gente? :)

2020-09-03 15:28 UTC, tyemykuga commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Teria o link do PR pra passar pra gente? :)

2020-09-03 16:17 UTC, eliasreis54 commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Sim, eu que fiz o merge.
Segue o link: https://github.com/dextra/challenges/pull/9

2020-09-03 16:18 UTC, eliasreis54 commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Sim, eu que fiz o merge.
Segue o link: dextra/challenges#9

2020-09-03 17:18 UTC, tyemykuga requested changes
Teria o link do PR pra passar pra gente? :)

2020-09-04 16:16 UTC, leandropaes commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Atualizado :)

2020-09-04 16:16 UTC, leandropaes commented on contributions/leandrolima/01.json
> +    "contributionLinkRepository": "https://github.com/dextra/challenges"
Atualizado :)

2020-09-04 19:11 UTC, eliasreis54 approved these changes

2020-09-08 12:27 UTC, tyemykuga approved these changes

2020-09-08 12:28 UTC, merged