Added contributions by Tiago Vilas Boas
dextra/dextraquario pull request #33
Opened 2020-09-04 16:49 UTC by tiagovilasboas

2020-09-04 16:57 UTC, tyemykuga commented on contributions/tiagovilasboas/01.json
> +    "contributionLinkRepository": "https://docs.google.com/document/d/1akT5Oj_5N-2WTOHbdqHEUXpUmIGPhEawbixt6DkoUeA"
Oi Tiago, obrigada por participar do Dextraquário.
A ideia é submeter somente os desafios criados nesse mês de setembro para nossa comemoração. :)

2020-09-04 16:57 UTC, tyemykuga commented on contributions/tiagovilasboas/02.json
> +    "contributionLinkRepository": "https://docs.google.com/document/d/1Amc8qFL50hULuaRB9XeFlMy-GoG_OYbe3a_2B0_ewwk"
Oi Tiago, obrigada por participar do Dextraquário.
A ideia é submeter somente os desafios criados nesse mês de setembro para nossa comemoração. :)

2020-09-04 16:58 UTC, tyemykuga commented on contributions/tiagovilasboas/05.json
> +    "contributionDescription": "Avaliação do teste técnico do candidato Felipe Rocha",
Nesse caso, não é legal colocar o nome do candidato.
Coloque somente o nome da pessoa de people connection que participou com você.

2020-09-04 16:58 UTC, tyemykuga commented on contributions/tiagovilasboas/04.json
> +    "contributionDescription": "Avaliação do teste técnico do candidato Marcio Henrique",
Nesse caso, não é legal colocar o nome do candidato.
Coloque somente o nome da pessoa de people connection que participou com você.

2020-09-04 16:58 UTC, tyemykuga commented on contributions/tiagovilasboas/03.json
> +    "contributionDescription": "Entrevista técnica do candidato Marcio Henrique",
Nesse caso, não é legal colocar o nome do candidato.
Coloque somente o nome da pessoa de people connection que participou com você.

2020-09-04 17:00 UTC, tyemykuga requested changes
Fiz alguns comentários.
Você pode conferir o regulamento aqui: https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view

2020-09-04 17:26 UTC, tiagovilasboas commented on contributions/tiagovilasboas/01.json
> +    "contributionLinkRepository": "https://docs.google.com/document/d/1akT5Oj_5N-2WTOHbdqHEUXpUmIGPhEawbixt6DkoUeA"
oi Tyemy, apesar do desafio ter sido criado em 2019, o mesmo sofreu alterações e também aprimoramentos nesse mês, mesmo assim não contaria?

2020-09-04 17:37 UTC, tiagovilasboas commented on contributions/tiagovilasboas/04.json
> +    "contributionDescription": "Avaliação do teste técnico do candidato Marcio Henrique",
Feito ;)

2020-09-04 17:37 UTC, tiagovilasboas commented on contributions/tiagovilasboas/03.json
> +    "contributionDescription": "Entrevista técnica do candidato Marcio Henrique",
Feito!

2020-09-04 18:50 UTC, tiagovilasboas commented on contributions/tiagovilasboas/02.json
> +    "contributionLinkRepository": "https://docs.google.com/document/d/1Amc8qFL50hULuaRB9XeFlMy-GoG_OYbe3a_2B0_ewwk"
Entendi, obrigado! =)

2020-09-08 12:26 UTC, tyemykuga approved these changes

2020-09-08 12:26 UTC, merged