Added Contribution by Leonardo Bilia
dextra/dextraquario pull request #35
Opened 2020-09-04 21:28 UTC by leonardobilia

2020-09-04 22:29 UTC, eliasreis54 commented on contributions/LeonardoBilia/contribution-01.json
> +    "contributionDescription": "Participação na entrevista do candidato Rafael Adolfo para vaga de iOS na data de 03/09/2020",
Olá Leonardo, obrigado pela contribuição!
Pedimos que **não** seja colocado o nome do candidato no PR, para não expor nomes. 
Você pode colocar o nome da pessoa de people connection que solicitou sua ajuda =)

2020-09-04 22:29 UTC, eliasreis54 requested changes
Ajustar o texto de decrição.

2020-09-05 17:55 UTC, leonardobilia commented on contributions/LeonardoBilia/contribution-01.json
> +    "contributionDescription": "Participação na entrevista do candidato Rafael Adolfo para vaga de iOS na data de 03/09/2020",
Legal Elias. Bem lembrado. 👍
Correção efetuada.

2020-09-08 12:26 UTC, tyemykuga approved these changes

2020-09-08 13:59 UTC, eliasreis54 approved these changes

2020-09-08 14:00 UTC, merged