incluir fellipe mendes
dextra/dextraquario pull request #60
Opened 2020-09-10 17:21 UTC by fellipemendes

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-10 19:45 UTC, tyemykuga commented on contributions/FellipeMendes/01.json
> +    "contributionDescription": "Correção de Teste QA feito 01/09/2020",
Oi Fellipe, tudo bem? Obrigada por contribuir para o aquário!

Você poderia, por favor, colocar o nome da pessoa do RH que você apoiou para podermos validar?
Obrigada!

2020-09-10 19:45 UTC, tyemykuga requested changes
Adicionar o nome da pessoa do RH para validação das entrevistas/análise de testes.

2020-09-10 19:53 UTC, fellipemendes commented on contributions/FellipeMendes/01.json
> +    "contributionDescription": "Correção de Teste QA feito 01/09/2020",
Feito!

2020-09-10 22:42 UTC, eliasreis54 commented
Verificado!

2020-09-10 22:42 UTC, eliasreis54 approved these changes

2020-09-13 14:43 UTC, tyemykuga approved these changes
Elias verificou :)

2020-09-14 14:44 UTC, merged