Desafios Tecnicos
dextra/dextraquario pull request #62
Opened 2020-09-10 20:31 UTC by vvalcristina

2020-09-10 22:06 UTC, eliasreis54 commented on contributions/Valeria Silva/01.json
> +    "contributionLinkRepository": "https://gitlab.dextra.com.br/dextra/dojo4admissions/tree/dextra-potter"
Esse repositório poderia ser público para a nossa organização? Não conseguimos ver o código dele, acredito estar privado.

2020-09-10 22:07 UTC, eliasreis54 commented on contributions/Valeria Silva/02.json
> +    "contributionLinkRepository": "https://github.com/vvalcristina/beheind_the_code/blob/master/README.md"
É possível compartilhar além do resultado o processo de resolução desse desafio também?

2020-09-10 22:08 UTC, eliasreis54 commented
Oi @vvalcristina muito obrigado pela sua contribuição! 
Deixei alguns comentários. =)

2020-09-10 22:08 UTC, eliasreis54 requested changes
Oi @vvalcristina muito obrigado pela sua contribuição!
Deixei alguns comentários. =)

2020-09-11 13:14 UTC, vvalcristina commented on contributions/Valeria Silva/02.json
> +    "contributionLinkRepository": "https://github.com/vvalcristina/beheind_the_code/blob/master/README.md"
Código compartilhado no repositorio

2020-09-11 13:14 UTC, vvalcristina commented on contributions/Valeria Silva/01.json
> +    "contributionLinkRepository": "https://gitlab.dextra.com.br/dextra/dojo4admissions/tree/dextra-potter"
Coloquei os links dos slides do Dojo. Achei mais adequado, já que auxiliei nos testes :D

2020-09-14 19:29 UTC, tyemykuga commented on contributions/Valeria Silva/02.json
> +    "contributionLinkRepository": "https://github.com/vvalcristina/beheind_the_code/blob/master/README.md"
Oi Valeria!

O link que você adicionou possui um outro link para o repositório do desafio. Nele só encontramos commits de outra pessoa e alguns até do mês de agosto (Lembrando que só vale desafios feitos no mês de Setembro!).
Essa participação não ficou condizente com as regras do evento e não será considerada. 
Poderia, por favor, remover o arquivo `contributions/Valeria Silva/02.json` para finalizarmos a submissão?

Obrigada!

2020-09-14 19:29 UTC, tyemykuga requested changes
Fiz um comentário sobre o item 02.

2020-09-14 19:36 UTC, vvalcristina commented on contributions/Valeria Silva/02.json
> +    "contributionLinkRepository": "https://github.com/vvalcristina/beheind_the_code/blob/master/README.md"
Oi tymey removi o item

2020-09-15 12:28 UTC, tyemykuga approved these changes

2020-09-15 12:28 UTC, tyemykuga approved these changes
Aprovado após os ajustes realizados.
@eliasreis54 pode validar?

2020-09-15 12:30 UTC, eliasreis54 approved these changes

2020-09-15 12:33 UTC, merged