[Fabio Rocha] Add a contribution (interview)
dextra/dextraquario pull request #72
Opened 2020-09-11 14:18 UTC by FabioRochaDextra

[Fabio Rocha] Add a contribution (interview)

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-11 14:40 UTC, eliasreis54 commented on contributions/fabiorocha/contribution-1.json
> +  "contributionDescription": "Entrevista para vaga Android (10/09 - 10:00h)",
Poderia, por favor, colocar a identificação da pessoa de people connection?

2020-09-11 14:41 UTC, eliasreis54 requested changes
Olá! @FabioRochaDextra, muito obrigado pela sua contribuição
Fiz um comentário =)

2020-09-11 15:00 UTC, FabioRochaDextra commented on contributions/fabiorocha/contribution-1.json
> +  "contributionDescription": "Entrevista para vaga Android (10/09 - 10:00h)",
Adicionado

2020-09-14 19:14 UTC, eliasreis54 approved these changes

2020-09-14 19:15 UTC, merged