[Julia Melo] Contribuicao dojos programa de estagio
dextra/dextraquario pull request #73
Opened 2020-09-11 15:15 UTC by julia-melo

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-14 19:32 UTC, eliasreis54 commented on contributions/Julia Melo/contribuicao2.json
> +  "contributionLinkRepository": "https://gitlab.dextra.com.br/dextra/dojo4admissions/merge_requests/1"
Oi @julia-melo! Muito obrigado pela sua contribuição?
O repositório poderia ser público para a nossa organização? 
Ou, há alguma apresentação de slides que seja possível compartilhar?
Digo isso porque fui tentar acessar o link e deu 404.

2020-09-14 19:32 UTC, eliasreis54 requested changes
OI @julia-melo deixei um pequeno comentário no PR =)

2020-09-15 13:03 UTC, julia-melo commented on contributions/Julia Melo/contribuicao2.json
> +  "contributionLinkRepository": "https://gitlab.dextra.com.br/dextra/dojo4admissions/merge_requests/1"
Hum, para dar a permissão é preciso abrir um chamado para a infra. Então vou compartilhar a apresentação de slides, que também foi reformulada, beleza?

2020-09-15 16:20 UTC, eliasreis54 commented on contributions/Julia Melo/contribuicao2.json
> +  "contributionLinkRepository": "https://gitlab.dextra.com.br/dextra/dojo4admissions/merge_requests/1"
Perfeito! =)

2020-09-16 15:35 UTC, merged