Entrevista QA
dextra/dextraquario pull request #75
Opened 2020-09-11 19:06 UTC by pcontiero

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-14 19:17 UTC, eliasreis54 commented on contributions/priscilacontiero/02.json
> +    "contributionLinkRepository":"https://github.com/suelyn-nogueira/desafio"
Pode remover esse link, tento o nome da pessoa de people connection a gente já consegue validar =)

2020-09-14 19:17 UTC, eliasreis54 commented on contributions/priscilacontiero/03.json
> +    "contributionLinkRepository": "https://github.com/Morphell/desafioQA_Dextra"
Pode remover esse link, tento o nome da pessoa de people connection a gente já consegue validar =)

2020-09-14 19:17 UTC, eliasreis54 requested changes
Olá @pcontiero! Muito obrigado pela sua contribuição!
Deixei 2 comentários! =)

2020-09-15 18:07 UTC, tyemykuga approved these changes
Arquivos ajustados.
@eliasreis54 pode validar das entrevistas?

2020-09-16 15:10 UTC, eliasreis54 commented
Eu confirmei as entrevistas! Pra mim ta ok! 
Mas acho que deu conflito... =\

2020-09-21 12:58 UTC, tyemykuga reviewed
@eliasreis54 ajustei o conflito da Pri, podemos mergear?

2020-09-21 13:03 UTC, eliasreis54 approved these changes

2020-09-21 13:03 UTC, merged