Solução dos desafios Covariant types, Comparator e Inheritance 1 e 2
dextra/dextraquario pull request #85
Opened 2020-09-14 21:52 UTC by DheCastro

Solução dos desafios Covariant types, Comparator e Inheritance 1 e 2 - HackerRank

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-16 15:25 UTC, tyemykuga requested changes
Olá Dhellano, tudo bem?

Agradecemos as contribuições que tem feito no Dextraquário, mas percebemos que alguns desafios que foram submetidos são muito simples.
O objetivo da iniciativa é que as pessoas se desafiem a fazer algo diferente, aprender algo novo, etc.
Vamos revisar todas as suas contribuições e se entendermos que não estão aderentes a ideia do projeto, ela serão removidas.

Obrigada!

2020-09-16 15:30 UTC, DheCastro commented
Olá Tyemy, tudo bem sim e com você?

Tranquilo, eu entendo. Eu tava pegando no hackerrank de forma aleatória (não conhecia o site). Então de fato tem umas um pouco mais complexas, outras bem mais fáceis e fui resolvendo e mandando. Mas entendo demais a colocação e não vejo problema. Totalmente compreensivo.

Vou fazer um filtro maior nos desafios e continuar colaborando da forma que puder. Estou com uns artigos pra mandar também, pra não ficar só nos desafios de código. Eu até já entrei em contato com o marketing como diz o regulamento, estou esperando resposta pra fazer o rascunho dos artigos no blog da Dextra.

Fico agradecido pelos esclarecimentos.

2020-09-16 15:33 UTC, eliasreis54 requested changes
Olá @DheCastro, muito obrigado pelas suas contribuições para o dextraquario.

Percebemos que os desafios que foram submetidos são bem simples para quem já tem o domínio da tecnologia.
O intuito desse projeto é que as pessoas se desafiem a sair da sua zona de conforto.
Sendo assim, vamos revisar suas contribuições para verificar a aderência ao projeto.

2020-09-16 15:37 UTC, DheCastro commented
Olá @eliasreis54 , tranquilo.

Como falei aí pra Tyemy, eu entendo. Estava pegando os desafios no hackerrank de forma aleatória (não conhecia o site). Então realmente tem tarefas um pouco mais complexas e outras muito fáceis. Mas compreendo e entendo que podem retirar as tarefas que mandei, sem problemas. =)

Vou filtrar melhor os desafios e continuar colaborando de uma melhor forma. Vou submeter meus artigos também lá pro blog e tentar colaborar com a comunidade em outros projetos.

Fico agradecido pela atenção e observação.

2020-09-21 13:00 UTC, closed without merging

2020-09-21 13:00 UTC, tyemykuga commented
Conforme comentários, o PR será fechado e os demais itens já submetidos serão revalidados.