contribution 1
dextra/dextraquario pull request #89
Opened 2020-09-15 01:14 UTC by erickmob

# Obrigado pela sua contribuição

### IMPORTANTE!!

Caso sua contribuição seja para o time de people connection em correção de teste ou bate papo em entrevista, **NÃO** coloque o nome do candidato no seu PR aqui para o repositório, coloque somente o nome da pessoa do time de People que você apoiou. Vamos manter as informações confidenciais. =)

Confira todas as regras em nosso [REGULAMENTO](https://drive.google.com/file/d/1km2JxZgbeSivb5_uaYCfuWdXi5sbyPV4/view?usp=sharing)

Obrigado.

2020-09-15 12:24 UTC, tyemykuga commented on contributions/erickoliveira/contribuicao-1.json
> +    // Available colors: [BLUE, RED, GREEN, YELLOW, PINK]
Bom dia Erick, tudo bem? Obrigada por contribuir como Dextraquario!

Peço por favor, que remova os comentários do arquivo

2020-09-15 12:25 UTC, tyemykuga commented on contributions/erickoliveira/contribuicao-1.json
> +    "contributionLinkRepository": "https://github.com/me50/erickmob/tree/a0f1e4e3338f978c3f8e81ce18d752fdf4127b7d"
O Repositório está privado, poderia deixar público por favor?

2020-09-15 12:25 UTC, tyemykuga requested changes
Erick, fiz alguns comentários.. poderia verificar?
Obrigada!

2020-09-15 12:33 UTC, erickmob commented on contributions/erickoliveira/contribuicao-1.json
> +    "contributionLinkRepository": "https://github.com/me50/erickmob/tree/a0f1e4e3338f978c3f8e81ce18d752fdf4127b7d"
Oi! Obrigado pelo aviso. 
eu acho que não vai dar.. é um exercício de um curso e acho que eles deixam privado para não plagiarem.. 
Beleza, vou ver outros desafios abertos.
Obrigado!

2020-09-23 15:58 UTC, tyemykuga commented
Como o @erickmob falou que o repositório não pode ser público, vou fechar o PR ok?
Qualquer coisa pode reabrir Erick. :)

Obrigada!

2020-09-23 15:58 UTC, closed without merging